### ISSUE TITLE
Change image name in docker-compose example

### ISSUE THREAD

**Issue by mjodmj** [hasnat/rest-ftp#1]
https://github.com/hasnat/rest-ftp/blob/587a8e3aeb6c7ce57d665e8ec47a1aa775825f08/docker-compose.yml#L5

Hi there, 
in the example you've typed wrong image name.     
Change `image: hasnat/restful-ftp` to `image: hasnat/rest-ftp`.

Regards
Marcin

**Comment by hasnat** [comment]
thank you for highlighting, fixing in #2
